### ISSUE TITLE
Problem with python urllib3/ssl and OpenSSL 0.9.8e

### ISSUE THREAD

**Issue by mclang** [wakatime/vim-wakatime#20]
I just updated wakatime vim plugin to the version 3.0.7 and started to get a lot of these errors:
```
Traceback (most recent call last):
  File "/root/.vim/bundle/vim-wakatime/plugin/packages/wakatime/wakatime-cli.py", line 20, in <module>
    sys.exit(wakatime.main(sys.argv))
  File "/root/.vim/bundle/vim-wakatime/plugin/packages/wakatime/wakatime/__init__.py", line 406, in main
    **vars(args)
  File "/root/.vim/bundle/vim-wakatime/plugin/packages/wakatime/wakatime/__init__.py", line 323, in send_heartbeat
    proxies=proxies)
  File "/root/.vim/bundle/vim-wakatime/plugin/packages/wakatime/wakatime/packages/requests/api.py", line 99, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/root/.vim/bundle/vim-wakatime/plugin/packages/wakatime/wakatime/packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/root/.vim/bundle/vim-wakatime/plugin/packages/wakatime/wakatime/packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/.vim/bundle/vim-wakatime/plugin/packages/wakatime/wakatime/packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/root/.vim/bundle/vim-wakatime/plugin/packages/wakatime/wakatime/packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/root/.vim/bundle/vim-wakatime/plugin/packages/wakatime/wakatime/packages/requests/packages/urllib3/connectionpool.py", line 529, in urlopen
    body=body, headers=headers)
  File "/root/.vim/bundle/vim-wakatime/plugin/packages/wakatime/wakatime/packages/requests/packages/urllib3/connectionpool.py", line 326, in _make_request
    self._validate_conn(conn)
  File "/root/.vim/bundle/vim-wakatime/plugin/packages/wakatime/wakatime/packages/requests/packages/urllib3/connectionpool.py", line 740, in _validate_conn
    conn.connect()
  File "/root/.vim/bundle/vim-wakatime/plugin/packages/wakatime/wakatime/packages/requests/packages/urllib3/connection.py", line 238, in connect
    ssl_version=resolved_ssl_version)
  File "/root/.vim/bundle/vim-wakatime/plugin/packages/wakatime/wakatime/packages/requests/packages/urllib3/util/ssl_.py", line 254, in ssl_wrap_socket
    return context.wrap_socket(sock)
  File "/usr/local/lib/python3.4/ssl.py", line 364, in wrap_socket
    _context=self)
  File "/usr/local/lib/python3.4/ssl.py", line 535, in __init__
    raise ValueError("check_hostname requires server_hostname, "
ValueError: check_hostname requires server_hostname, but it's not supported by your OpenSSL library
```
I don't get these errors when using version 3.0.6 so the cause is probably the change from urllib2 to the requests library... Proper thing to do would be update my OpenSSL but alas, that is not possible because I'm running CentOS 5.

Is there any way around this so that I can keep using newer versions?

**Comment by alanhamlett** [comment]
Can you try with the latest version of the plugin? Should have been fixed with shazow/urllib3#526

**Comment by mclang** [comment]
First updating vim-wakatime didn't solve the problem, but after I updated also python wakatime using pip (3.0.4 -> 4.0.0) and did clean install/update of the vim plugin, the problem has not surfaced again.

Thank you!

**Comment by alanhamlett** [comment]
vim-wakatime comes bundled with the python wakatime package, so you can uninstall wakatime with `pip uninstall wakatime` and the vim plugin will still work. Glad it's fixed now!
